language: python
dist: xenial  # required for Python >= 3.7
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - python: 2.6
    dist: trusty
  - python: 2.7
  - python: 3.3
    dist: trusty
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: pypy
    dist: trusty
  - python: pypy3
    dist: trusty
  - python: 3.7
    services:
      - docker
    env: BUILD_SDIST=true
  - name: Python 2.7.12 on macOS
    os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - name: Python 3.5.5 on macOS
    os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.5
  - name: Python 3.6.5 on macOS
    os: osx
    language: objective-c
    env: PYENV_VERSION=3.6.5
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: releases
  api_key:
    secure: QiadMGAmtPw+Ut7LWqa3U/tImPIgiPH79mM9o8DGBckcacp9HkDYvCGuOjs5hZbCBBuQ6IAkikotS8iCSwHey1GK9jSDbpgKvVGiACdp8HNhitY8V/S3e1UukDlMeu+Q7vCJtynSGX0BJuiOQB8ZQyQ2HEZ7kMQgTLCEO1Uljhc=
  file:
    - dist/*.whl
    - dist/*.tar.gz
  file_glob: true
  on:
    repo: simplejson/simplejson
    tags: true
  skip_cleanup: true
